// source: tibc/core/types/v1/genesis.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var gogoproto_gogo_pb = require('../../../../gogoproto/gogo_pb.js');
goog.object.extend(proto, gogoproto_gogo_pb);
var tibc_core_client_v1_genesis_pb = require('../../../../tibc/core/client/v1/genesis_pb.js');
goog.object.extend(proto, tibc_core_client_v1_genesis_pb);
var tibc_core_packet_v1_genesis_pb = require('../../../../tibc/core/packet/v1/genesis_pb.js');
goog.object.extend(proto, tibc_core_packet_v1_genesis_pb);
var tibc_core_routing_v1_genesis_pb = require('../../../../tibc/core/routing/v1/genesis_pb.js');
goog.object.extend(proto, tibc_core_routing_v1_genesis_pb);
goog.exportSymbol('proto.tibc.core.types.v1.GenesisState', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tibc.core.types.v1.GenesisState = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tibc.core.types.v1.GenesisState, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tibc.core.types.v1.GenesisState.displayName = 'proto.tibc.core.types.v1.GenesisState';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tibc.core.types.v1.GenesisState.prototype.toObject = function(opt_includeInstance) {
  return proto.tibc.core.types.v1.GenesisState.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tibc.core.types.v1.GenesisState} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tibc.core.types.v1.GenesisState.toObject = function(includeInstance, msg) {
  var f, obj = {
    clientGenesis: (f = msg.getClientGenesis()) && tibc_core_client_v1_genesis_pb.GenesisState.toObject(includeInstance, f),
    packetGenesis: (f = msg.getPacketGenesis()) && tibc_core_packet_v1_genesis_pb.GenesisState.toObject(includeInstance, f),
    routingGenesis: (f = msg.getRoutingGenesis()) && tibc_core_routing_v1_genesis_pb.GenesisState.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tibc.core.types.v1.GenesisState}
 */
proto.tibc.core.types.v1.GenesisState.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tibc.core.types.v1.GenesisState;
  return proto.tibc.core.types.v1.GenesisState.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tibc.core.types.v1.GenesisState} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tibc.core.types.v1.GenesisState}
 */
proto.tibc.core.types.v1.GenesisState.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new tibc_core_client_v1_genesis_pb.GenesisState;
      reader.readMessage(value,tibc_core_client_v1_genesis_pb.GenesisState.deserializeBinaryFromReader);
      msg.setClientGenesis(value);
      break;
    case 3:
      var value = new tibc_core_packet_v1_genesis_pb.GenesisState;
      reader.readMessage(value,tibc_core_packet_v1_genesis_pb.GenesisState.deserializeBinaryFromReader);
      msg.setPacketGenesis(value);
      break;
    case 4:
      var value = new tibc_core_routing_v1_genesis_pb.GenesisState;
      reader.readMessage(value,tibc_core_routing_v1_genesis_pb.GenesisState.deserializeBinaryFromReader);
      msg.setRoutingGenesis(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tibc.core.types.v1.GenesisState.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tibc.core.types.v1.GenesisState.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tibc.core.types.v1.GenesisState} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tibc.core.types.v1.GenesisState.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getClientGenesis();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      tibc_core_client_v1_genesis_pb.GenesisState.serializeBinaryToWriter
    );
  }
  f = message.getPacketGenesis();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      tibc_core_packet_v1_genesis_pb.GenesisState.serializeBinaryToWriter
    );
  }
  f = message.getRoutingGenesis();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      tibc_core_routing_v1_genesis_pb.GenesisState.serializeBinaryToWriter
    );
  }
};


/**
 * optional tibc.core.client.v1.GenesisState client_genesis = 1;
 * @return {?proto.tibc.core.client.v1.GenesisState}
 */
proto.tibc.core.types.v1.GenesisState.prototype.getClientGenesis = function() {
  return /** @type{?proto.tibc.core.client.v1.GenesisState} */ (
    jspb.Message.getWrapperField(this, tibc_core_client_v1_genesis_pb.GenesisState, 1));
};


/**
 * @param {?proto.tibc.core.client.v1.GenesisState|undefined} value
 * @return {!proto.tibc.core.types.v1.GenesisState} returns this
*/
proto.tibc.core.types.v1.GenesisState.prototype.setClientGenesis = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tibc.core.types.v1.GenesisState} returns this
 */
proto.tibc.core.types.v1.GenesisState.prototype.clearClientGenesis = function() {
  return this.setClientGenesis(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tibc.core.types.v1.GenesisState.prototype.hasClientGenesis = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional tibc.core.packet.v1.GenesisState packet_genesis = 3;
 * @return {?proto.tibc.core.packet.v1.GenesisState}
 */
proto.tibc.core.types.v1.GenesisState.prototype.getPacketGenesis = function() {
  return /** @type{?proto.tibc.core.packet.v1.GenesisState} */ (
    jspb.Message.getWrapperField(this, tibc_core_packet_v1_genesis_pb.GenesisState, 3));
};


/**
 * @param {?proto.tibc.core.packet.v1.GenesisState|undefined} value
 * @return {!proto.tibc.core.types.v1.GenesisState} returns this
*/
proto.tibc.core.types.v1.GenesisState.prototype.setPacketGenesis = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tibc.core.types.v1.GenesisState} returns this
 */
proto.tibc.core.types.v1.GenesisState.prototype.clearPacketGenesis = function() {
  return this.setPacketGenesis(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tibc.core.types.v1.GenesisState.prototype.hasPacketGenesis = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional tibc.core.routing.v1.GenesisState routing_genesis = 4;
 * @return {?proto.tibc.core.routing.v1.GenesisState}
 */
proto.tibc.core.types.v1.GenesisState.prototype.getRoutingGenesis = function() {
  return /** @type{?proto.tibc.core.routing.v1.GenesisState} */ (
    jspb.Message.getWrapperField(this, tibc_core_routing_v1_genesis_pb.GenesisState, 4));
};


/**
 * @param {?proto.tibc.core.routing.v1.GenesisState|undefined} value
 * @return {!proto.tibc.core.types.v1.GenesisState} returns this
*/
proto.tibc.core.types.v1.GenesisState.prototype.setRoutingGenesis = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tibc.core.types.v1.GenesisState} returns this
 */
proto.tibc.core.types.v1.GenesisState.prototype.clearRoutingGenesis = function() {
  return this.setRoutingGenesis(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tibc.core.types.v1.GenesisState.prototype.hasRoutingGenesis = function() {
  return jspb.Message.getField(this, 4) != null;
};


goog.object.extend(exports, proto.tibc.core.types.v1);
